// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person_msg_ext.proto

package com.demo.protobuf.model;

public final class PersonProtobufExt {
  private PersonProtobufExt() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.demo.protobuf.model.PersonProtobufExt.PersonExt.persionExt);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonExtOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PersonExt)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string city = 1;</code>
     */
    boolean hasCity();
    /**
     * <code>required string city = 1;</code>
     */
    java.lang.String getCity();
    /**
     * <code>required string city = 1;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();
  }
  /**
   * Protobuf type {@code PersonExt}
   */
  public  static final class PersonExt extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PersonExt)
      PersonExtOrBuilder {
    // Use PersonExt.newBuilder() to construct.
    private PersonExt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PersonExt() {
      city_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PersonExt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              city_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.protobuf.model.PersonProtobufExt.internal_static_PersonExt_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.protobuf.model.PersonProtobufExt.internal_static_PersonExt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.protobuf.model.PersonProtobufExt.PersonExt.class, com.demo.protobuf.model.PersonProtobufExt.PersonExt.Builder.class);
    }

    private int bitField0_;
    public static final int CITY_FIELD_NUMBER = 1;
    private volatile java.lang.Object city_;
    /**
     * <code>required string city = 1;</code>
     */
    public boolean hasCity() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string city = 1;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          city_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string city = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, city_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, city_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.demo.protobuf.model.PersonProtobufExt.PersonExt)) {
        return super.equals(obj);
      }
      com.demo.protobuf.model.PersonProtobufExt.PersonExt other = (com.demo.protobuf.model.PersonProtobufExt.PersonExt) obj;

      boolean result = true;
      result = result && (hasCity() == other.hasCity());
      if (hasCity()) {
        result = result && getCity()
            .equals(other.getCity());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasCity()) {
        hash = (37 * hash) + CITY_FIELD_NUMBER;
        hash = (53 * hash) + getCity().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.protobuf.model.PersonProtobufExt.PersonExt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.protobuf.model.PersonProtobufExt.PersonExt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.protobuf.model.PersonProtobufExt.PersonExt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.protobuf.model.PersonProtobufExt.PersonExt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.protobuf.model.PersonProtobufExt.PersonExt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.protobuf.model.PersonProtobufExt.PersonExt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.protobuf.model.PersonProtobufExt.PersonExt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.protobuf.model.PersonProtobufExt.PersonExt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.protobuf.model.PersonProtobufExt.PersonExt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.demo.protobuf.model.PersonProtobufExt.PersonExt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.protobuf.model.PersonProtobufExt.PersonExt prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PersonExt}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PersonExt)
        com.demo.protobuf.model.PersonProtobufExt.PersonExtOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.demo.protobuf.model.PersonProtobufExt.internal_static_PersonExt_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.demo.protobuf.model.PersonProtobufExt.internal_static_PersonExt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.demo.protobuf.model.PersonProtobufExt.PersonExt.class, com.demo.protobuf.model.PersonProtobufExt.PersonExt.Builder.class);
      }

      // Construct using com.demo.protobuf.model.PersonProtobufExt.PersonExt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        city_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.demo.protobuf.model.PersonProtobufExt.internal_static_PersonExt_descriptor;
      }

      public com.demo.protobuf.model.PersonProtobufExt.PersonExt getDefaultInstanceForType() {
        return com.demo.protobuf.model.PersonProtobufExt.PersonExt.getDefaultInstance();
      }

      public com.demo.protobuf.model.PersonProtobufExt.PersonExt build() {
        com.demo.protobuf.model.PersonProtobufExt.PersonExt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.demo.protobuf.model.PersonProtobufExt.PersonExt buildPartial() {
        com.demo.protobuf.model.PersonProtobufExt.PersonExt result = new com.demo.protobuf.model.PersonProtobufExt.PersonExt(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.city_ = city_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.protobuf.model.PersonProtobufExt.PersonExt) {
          return mergeFrom((com.demo.protobuf.model.PersonProtobufExt.PersonExt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.protobuf.model.PersonProtobufExt.PersonExt other) {
        if (other == com.demo.protobuf.model.PersonProtobufExt.PersonExt.getDefaultInstance()) return this;
        if (other.hasCity()) {
          bitField0_ |= 0x00000001;
          city_ = other.city_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCity()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.demo.protobuf.model.PersonProtobufExt.PersonExt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.demo.protobuf.model.PersonProtobufExt.PersonExt) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object city_ = "";
      /**
       * <code>required string city = 1;</code>
       */
      public boolean hasCity() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string city = 1;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            city_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string city = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string city = 1;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string city = 1;</code>
       */
      public Builder clearCity() {
        bitField0_ = (bitField0_ & ~0x00000001);
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>required string city = 1;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        city_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PersonExt)
    }

    // @@protoc_insertion_point(class_scope:PersonExt)
    private static final com.demo.protobuf.model.PersonProtobufExt.PersonExt DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.protobuf.model.PersonProtobufExt.PersonExt();
    }

    public static com.demo.protobuf.model.PersonProtobufExt.PersonExt getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PersonExt>
        PARSER = new com.google.protobuf.AbstractParser<PersonExt>() {
      public PersonExt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PersonExt(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PersonExt> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PersonExt> getParserForType() {
      return PARSER;
    }

    public com.demo.protobuf.model.PersonProtobufExt.PersonExt getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    public static final int PERSIONEXT_FIELD_NUMBER = 101;
    /**
     * <code>extend .Person { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.demo.protobuf.model.PersonProtobuf.Person,
        com.demo.protobuf.model.PersonProtobufExt.PersonExt> persionExt = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          com.demo.protobuf.model.PersonProtobufExt.PersonExt.getDefaultInstance(),
          0,
          com.demo.protobuf.model.PersonProtobufExt.PersonExt.class,
          com.demo.protobuf.model.PersonProtobufExt.PersonExt.getDefaultInstance());
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonExt_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonExt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024person_msg_ext.proto\032\020person_msg.proto" +
      "\"B\n\tPersonExt\022\014\n\004city\030\001 \002(\t2\'\n\npersionEx" +
      "t\022\007.Person\030e \001(\0132\n.PersonExtB,\n\027com.demo" +
      ".protobuf.modelB\021PersonProtobufExt"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.demo.protobuf.model.PersonProtobuf.getDescriptor(),
        }, assigner);
    internal_static_PersonExt_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PersonExt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonExt_descriptor,
        new java.lang.String[] { "City", });
    com.demo.protobuf.model.PersonProtobuf.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
